development:
  adapter: redis
  url: redis://192.168.92.131:6379/1

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: quote_editor_production
